OK_STATUS = 'O'
WARNING_STATUS = 'W'
CRITICAL_STATUS = 'C'

ALL_STATUS = (OK_STATUS, WARNING_STATUS, CRITICAL_STATUS)

RESULT_STATUS = (
    (OK_STATUS, 'Ok'),
    (WARNING_STATUS, 'Warning'),
    (CRITICAL_STATUS, 'Critical'),
)